import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
export const baseUrl = "https://anwary-backend.pearlnestestates.com";

// Define base API configuration
export const apiSlice = createApi({
    reducerPath: 'api', // unique key in store
    baseQuery: fetchBaseQuery({ baseUrl: baseUrl }),
    tagTypes: ["Destinations", "Contact", "Booking"],
    endpoints: (builder) => ({
        // Destinations
        getDestinations: builder.query({
            query: ({ page, limit }) => `/destination?page=${page}&limit=${limit}`,
            providesTags: ["Destinations"]
        }),

        addDestination: builder.mutation({
            query: (data) => ({
                url: '/destination',
                method: 'POST',
                body: data,
            }),
            invalidatesTags: ["Destinations"]
        }),

        deleteDestination: builder.mutation({
            query: (id) => ({
                url: `/destination/${id}`,
                method: 'DELETE',
            }),
            invalidatesTags: ["Destinations"]
        }),

        //Contact
        addContact: builder.mutation({
            query: (data) => ({
                url: '/contact',
                method: 'POST',
                body: data,
            }),
            invalidatesTags: ["Contact"]
        }),

        //Booking
        addBooking: builder.mutation({
            query: (data) => ({
                url: '/booking/create',
                method: 'POST',
                body: data,
            }),
            invalidatesTags: ["Booking"]
        }),
    }),
});

// Export hooks auto-generated by RTK Query
export const {
    useGetDestinationsQuery,
    useAddDestinationMutation,
    useDeleteDestinationMutation,
    useAddContactMutation,
    useAddBookingMutation,
} = apiSlice;
